theme: jekyll-theme-cayman
title: Liquan Wang
email: lwang831@gatech.edu

show_downloads: "true"
github:
  cv_url: https://yunchunchen.github.io/CV/CV.pdf
  github_url: https://github.com/YunChunChen
  google_scholar_url: None
  dblp_url: https://dblp.uni-trier.de/pers/hd/c/Chen:Yun=Chun
  linkedin_url: https://www.linkedin.com/in/yun-chun-chen-615075164/
